import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './styles.css'
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Revise Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Bitcount+Prop+Double:wght@100..900&family=Exile&family=Jost:ital,wght@0,100..900;1,100..900&family=Playwrite+PL:wght@100..400&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
</head> */}
{/* <head>
 <script src="/feature.js"></script>
</head> */}

<head>
  {/* <link rel='stylesheet' href="/style.css"></link> */}
   <script src="/script.js" async></script>
</head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       
        <h1 style={{color:"green"}}>Comman Layout for RootLayout</h1>
         <Link href='/home'>Home Page</Link>
        {children}
      </body>
     
    </html>
  );
}
