import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './styles.css'
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Revise Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       
        <h1 style={{color:"green"}}>Comman Layout for RootLayout</h1>
         <Link href='/home'>Home Page</Link>
        {children}
      </body>
    </html>
  );
}
